[package]
name = "legal-ai-assistant"
version = "0.1.0"
description = "A secure, private AI assistant for legal professionals"
authors = ["Legal AI Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.8.0", features = [] }

[dependencies]
tauri = { version = "2.8.0", features = ["tray-icon"] }
tauri-plugin-fs = "2.4.2"
tauri-plugin-dialog = "2.4.0"
tauri-plugin-shell = "2.4.0"
tauri-plugin-os = "2.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
regex = "1"
lazy_static = "1.5"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
sysinfo = "0.37"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
async-trait = "0.1"
candle-core = "0.9"
candle-transformers = "0.9" 
candle-nn = "0.9"
hf-hub = { version = "0.4", features = ["tokio"] }
tokenizers = "0.22"
dirs = "6.0"
nvml-wrapper = "0.11"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "legal-ai-assistant"
path = "src/main.rs"
