# PII Exclusions Configuration
# This file defines terms and patterns that should NOT be flagged as PII
# Prevents legal terms, common locations, and standard phrases from being redacted

[exclusions]
# Geographic locations and jurisdictions - US
locations = [
    "United States",
    "New York",
    "California",
    "Texas",
    "Florida",
    "Washington",
    "District of Columbia",
    "Washington DC",
    "Supreme Court",
    "Federal Court",
    "Court of Appeals",
    "District Court",
    "Circuit Court",
    "Northern District",
    "Southern District",
    "Eastern District",
    "Western District",
]

# Geographic locations and jurisdictions - UK
uk_locations = [
    "United Kingdom",
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "Great Britain",
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Cardiff",
    "Belfast",
    "Glasgow",
    "Liverpool",
    "Supreme Court of the United Kingdom",
    "Court of Appeal",
    "High Court",
    "Crown Court",
    "Magistrates' Court",
    "Sheriff Court",
    "Court of Session",
]

# Geographic locations and jurisdictions - EU
eu_locations = [
    # General EU
    "European Union",
    "European Economic Area",
    "Schengen Area",
    
    # EU Countries (English)
    "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic",
    "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
    "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg",
    "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia",
    "Slovenia", "Spain", "Sweden",
    
    # Major EU Cities
    "Brussels", "Strasbourg", "Luxembourg City", "Frankfurt",
    "Paris", "Berlin", "Rome", "Madrid", "Amsterdam", "Vienna",
    "Warsaw", "Budapest", "Prague", "Lisbon", "Athens", "Copenhagen",
    "Stockholm", "Helsinki", "Dublin", "Bucharest", "Sofia",
    
    # EU Courts (English)
    "European Court of Justice",
    "Court of Justice of the European Union",
    "General Court",
    "European Court of Human Rights",
    
    # EU Courts (French)
    "Cour de Justice de l'Union Européenne",
    "Cour de Justice Européenne",
    "Tribunal de l'Union Européenne",
    "Cour Européenne des Droits de l'Homme",
    
    # EU Courts (German)
    "Europäischer Gerichtshof",
    "Gerichtshof der Europäischen Union",
    "Europäisches Gericht",
    "Europäischer Gerichtshof für Menschenrechte",
    
    # EU Courts (Spanish)
    "Tribunal de Justicia de la Unión Europea",
    "Tribunal General",
    "Tribunal Europeo de Derechos Humanos",
    
    # EU Courts (Italian)
    "Corte di Giustizia dell'Unione Europea",
    "Tribunale dell'Unione Europea",
    "Corte Europea dei Diritti dell'Uomo",
    
    # EU Courts (Dutch)
    "Hof van Justitie van de Europese Unie",
    "Gerecht van de Europese Unie",
    "Europees Hof voor de Rechten van de Mens",
    
    # EU Courts (Polish)
    "Trybunał Sprawiedliwości Unii Europejskiej",
    "Sąd Unii Europejskiej",
    "Europejski Trybunał Praw Człowieka",
]

# Legal terms - UK
uk_legal_terms = [
    "Data Protection Act",
    "DPA 2018",
    "UK GDPR",
    "Information Commissioner's Office",
    "ICO",
    "Data Protection Officer",
    "DPO",
    "Data Controller",
    "Data Processor",
    "Subject Access Request",
    "SAR",
    "Right to be Forgotten",
    "Right to Erasure",
    "Lawful Basis",
    "Legitimate Interest",
    "Privacy and Electronic Communications Regulations",
    "PECR",
    "Freedom of Information Act",
    "FOIA",
    "Human Rights Act",
    "Magna Carta",
    "Bill of Rights 1689",
    "Parliamentary Sovereignty",
    "Rule of Law",
    "Common Law",
    "Statute Law",
    "Case Law",
    "Precedent",
    "Queen's Counsel",
    "King's Counsel",
    "QC",
    "KC",
    "Solicitor",
    "Barrister",
    "Lord Chancellor",
    "Attorney General",
    "Director of Public Prosecutions",
    "Crown Prosecution Service",
    "CPS",
    "Serious Fraud Office",
    "SFO",
    "Financial Conduct Authority",
    "FCA",
    "Prudential Regulation Authority",
    "PRA",
]

# Legal terms and constitutional references - US
legal_terms = [
    "First Amendment",
    "Second Amendment",
    "Fourth Amendment",
    "Fifth Amendment",
    "Sixth Amendment",
    "Fourteenth Amendment",
    "Supreme Court",
    "Federal Court",
    "Court of Appeals",
    "Justice Department",
    "Department of Justice",
    "Attorney General",
    "District Attorney",
    "Public Defender",
    "Chief Justice",
    "Associate Justice",
    "Circuit Judge",
    "Magistrate Judge",
    "United States Attorney",
    "Federal Bureau of Investigation",
    "Internal Revenue Service",
    "Securities and Exchange Commission",
    "Federal Trade Commission",
    "Equal Employment Opportunity Commission",
]

# Legal terms - EU (English)
eu_legal_terms_en = [
    "General Data Protection Regulation",
    "GDPR",
    "Data Protection Directive",
    "ePrivacy Directive",
    "Digital Services Act",
    "Digital Markets Act",
    "AI Act",
    "Article 6 GDPR",
    "Article 7 GDPR",
    "Article 13 GDPR",
    "Article 15 GDPR",
    "Article 17 GDPR",
    "Right to be Forgotten",
    "Right to Erasure",
    "Data Subject Access Request",
    "DSAR",
    "Data Protection Officer",
    "DPO",
    "Data Controller",
    "Data Processor",
    "Supervisory Authority",
    "Lead Supervisory Authority",
    "European Data Protection Board",
    "EDPB",
    "European Data Protection Supervisor",
    "EDPS",
    "Standard Contractual Clauses",
    "SCC",
    "Binding Corporate Rules",
    "BCR",
    "Data Protection Impact Assessment",
    "DPIA",
    "Legitimate Interest",
    "Legal Basis",
    "Treaty on European Union",
    "TEU",
    "Treaty on the Functioning of the European Union",
    "TFEU",
    "Charter of Fundamental Rights",
    "European Convention on Human Rights",
    "ECHR",
]

# Legal terms - German
eu_legal_terms_de = [
    "Datenschutz-Grundverordnung",
    "DSGVO",
    "Bundesdatenschutzgesetz",
    "BDSG",
    "Datenschutzbeauftragter",
    "Verantwortlicher",
    "Auftragsverarbeiter",
    "Betroffener",
    "Auskunftsrecht",
    "Recht auf Vergessenwerden",
    "Recht auf Löschung",
    "Einwilligung",
    "Berechtigtes Interesse",
    "Aufsichtsbehörde",
    "Bundesverfassungsgericht",
    "Bundesgerichtshof",
    "Landgericht",
    "Amtsgericht",
    "Staatsanwaltschaft",
    "Grundgesetz",
    "Artikel 1 Grundgesetz",
    "Menschenwürde",
]

# Legal terms - French
eu_legal_terms_fr = [
    "Règlement Général sur la Protection des Données",
    "RGPD",
    "Commission Nationale de l'Informatique et des Libertés",
    "CNIL",
    "Délégué à la Protection des Données",
    "DPD",
    "Responsable de Traitement",
    "Sous-traitant",
    "Personne Concernée",
    "Droit d'Accès",
    "Droit à l'Effacement",
    "Droit à l'Oubli",
    "Consentement",
    "Intérêt Légitime",
    "Autorité de Contrôle",
    "Conseil d'État",
    "Cour de Cassation",
    "Tribunal Judiciaire",
    "Procureur de la République",
    "Code Civil",
    "Code Pénal",
]

# Legal terms - Spanish
eu_legal_terms_es = [
    "Reglamento General de Protección de Datos",
    "RGPD",
    "Agencia Española de Protección de Datos",
    "AEPD",
    "Delegado de Protección de Datos",
    "DPD",
    "Responsable del Tratamiento",
    "Encargado del Tratamiento",
    "Interesado",
    "Derecho de Acceso",
    "Derecho al Olvido",
    "Derecho de Supresión",
    "Consentimiento",
    "Interés Legítimo",
    "Autoridad de Control",
    "Tribunal Constitucional",
    "Tribunal Supremo",
    "Audiencia Provincial",
    "Juzgado de Primera Instancia",
    "Fiscalía",
    "Constitución Española",
]

# Legal terms - Italian
eu_legal_terms_it = [
    "Regolamento Generale sulla Protezione dei Dati",
    "GDPR",
    "Garante per la Protezione dei Dati Personali",
    "Responsabile della Protezione dei Dati",
    "RPD",
    "Titolare del Trattamento",
    "Responsabile del Trattamento",
    "Interessato",
    "Diritto di Accesso",
    "Diritto all'Oblio",
    "Diritto alla Cancellazione",
    "Consenso",
    "Interesse Legittimo",
    "Autorità di Controllo",
    "Corte Costituzionale",
    "Corte Suprema di Cassazione",
    "Tribunale",
    "Procura della Repubblica",
    "Costituzione Italiana",
    "Codice Civile",
    "Codice Penale",
]

# Legal terms - Dutch
eu_legal_terms_nl = [
    "Algemene Verordening Gegevensbescherming",
    "AVG",
    "Autoriteit Persoonsgegevens",
    "AP",
    "Functionaris voor Gegevensbescherming",
    "FG",
    "Verwerkingsverantwoordelijke",
    "Verwerker",
    "Betrokkene",
    "Recht op Inzage",
    "Recht op Vergetelheid",
    "Recht op Wissing",
    "Toestemming",
    "Gerechtvaardigd Belang",
    "Toezichthoudende Autoriteit",
    "Hoge Raad",
    "Rechtbank",
    "Openbaar Ministerie",
    "Grondwet",
    "Burgerlijk Wetboek",
]

# Legal terms - Polish
eu_legal_terms_pl = [
    "Ogólne Rozporządzenie o Ochronie Danych",
    "RODO",
    "Urząd Ochrony Danych Osobowych",
    "UODO",
    "Inspektor Ochrony Danych",
    "IOD",
    "Administrator Danych",
    "Procesor Danych",
    "Osoba Której Dane Dotyczą",
    "Prawo Dostępu",
    "Prawo do Bycia Zapomnianym",
    "Prawo do Usunięcia",
    "Zgoda",
    "Prawnie Uzasadniony Interes",
    "Organ Nadzorczy",
    "Trybunał Konstytucyjny",
    "Sąd Najwyższy",
    "Sąd Okręgowy",
    "Prokuratura",
    "Konstytucja",
    "Kodeks Cywilny",
    "Kodeks Karny",
]

# Government organizations and agencies - US
organizations = [
    "United States Government",
    "Federal Bureau of Investigation",
    "Central Intelligence Agency",
    "National Security Agency",
    "Department of Defense",
    "Department of State",
    "Department of Treasury",
    "Department of Justice",
    "Environmental Protection Agency",
    "Food and Drug Administration",
    "Federal Aviation Administration",
    "Federal Communications Commission",
]

# Government organizations and agencies - EU (English)
eu_organizations_en = [
    "European Commission",
    "European Parliament",
    "Council of the European Union",
    "European Council",
    "European Central Bank",
    "European Investment Bank",
    "European Court of Auditors",
    "European Ombudsman",
    "European Data Protection Board",
    "European Data Protection Supervisor",
    "European Medicines Agency",
    "European Banking Authority",
    "European Securities and Markets Authority",
    "European Insurance and Occupational Pensions Authority",
    "European Aviation Safety Agency",
    "European Food Safety Authority",
    "European Environment Agency",
    "European Police Office",
    "Europol",
    "European Public Prosecutor's Office",
    "EPPO",
    "European Border and Coast Guard Agency",
    "Frontex",
    "European Asylum Support Office",
    "EASO",
]

# EU Organizations - French
eu_organizations_fr = [
    "Commission Européenne",
    "Parlement Européen",
    "Conseil de l'Union Européenne",
    "Conseil Européen",
    "Banque Centrale Européenne",
    "Banque Européenne d'Investissement",
    "Cour des Comptes Européenne",
    "Médiateur Européen",
    "Comité Européen de la Protection des Données",
    "Contrôleur Européen de la Protection des Données",
    "Agence Européenne des Médicaments",
    "Office Européen de Police",
    "Parquet Européen",
]

# EU Organizations - German
eu_organizations_de = [
    "Europäische Kommission",
    "Europäisches Parlament",
    "Rat der Europäischen Union",
    "Europäischer Rat",
    "Europäische Zentralbank",
    "Europäische Investitionsbank",
    "Europäischer Rechnungshof",
    "Europäischer Bürgerbeauftragter",
    "Europäischer Datenschutzausschuss",
    "Europäischer Datenschutzbeauftragter",
    "Europäische Arzneimittel-Agentur",
    "Europäisches Polizeiamt",
    "Europäische Staatsanwaltschaft",
]

# EU Organizations - Spanish
eu_organizations_es = [
    "Comisión Europea",
    "Parlamento Europeo",
    "Consejo de la Unión Europea",
    "Consejo Europeo",
    "Banco Central Europeo",
    "Banco Europeo de Inversiones",
    "Tribunal de Cuentas Europeo",
    "Defensor del Pueblo Europeo",
    "Comité Europeo de Protección de Datos",
    "Supervisor Europeo de Protección de Datos",
    "Agencia Europea de Medicamentos",
    "Oficina Europea de Policía",
    "Fiscalía Europea",
]

# EU Organizations - Italian
eu_organizations_it = [
    "Commissione Europea",
    "Parlamento Europeo",
    "Consiglio dell'Unione Europea",
    "Consiglio Europeo",
    "Banca Centrale Europea",
    "Banca Europea per gli Investimenti",
    "Corte dei Conti Europea",
    "Mediatore Europeo",
    "Comitato Europeo per la Protezione dei Dati",
    "Garante Europeo della Protezione dei Dati",
    "Agenzia Europea per i Medicinali",
    "Ufficio Europeo di Polizia",
    "Procura Europea",
]

# EU Organizations - Dutch
eu_organizations_nl = [
    "Europese Commissie",
    "Europees Parlement",
    "Raad van de Europese Unie",
    "Europese Raad",
    "Europese Centrale Bank",
    "Europese Investeringsbank",
    "Europese Rekenkamer",
    "Europese Ombudsman",
    "Europese Commissie voor Gegevensbescherming",
    "Europese Toezichthouder voor Gegevensbescherming",
    "Europees Geneesmiddelenbureau",
    "Europese Politiedienst",
    "Europees Openbaar Ministerie",
]

# EU Organizations - Polish
eu_organizations_pl = [
    "Komisja Europejska",
    "Parlament Europejski",
    "Rada Unii Europejskiej",
    "Rada Europejska",
    "Europejski Bank Centralny",
    "Europejski Bank Inwestycyjny",
    "Europejski Trybunał Obrachunkowy",
    "Europejski Rzecznik Praw Obywatelskich",
    "Europejska Rada Ochrony Danych",
    "Europejski Inspektor Ochrony Danych",
    "Europejska Agencja Leków",
    "Europejski Urząd Policji",
    "Prokuratura Europejska",
]

# National Data Protection Authorities
data_protection_authorities = [
    # France
    "Commission Nationale de l'Informatique et des Libertés",
    "CNIL",
    
    # Germany
    "Bundesbeauftragter für den Datenschutz und die Informationsfreiheit",
    "BfDI",
    
    # Spain
    "Agencia Española de Protección de Datos",
    "AEPD",
    
    # Italy
    "Garante per la Protezione dei Dati Personali",
    
    # Netherlands
    "Autoriteit Persoonsgegevens",
    
    # Poland
    "Urząd Ochrony Danych Osobowych",
    "UODO",
    
    # Belgium
    "Autorité de Protection des Données",
    "Gegevensbeschermingsautoriteit",
    "APD",
    "GBA",
    
    # Austria
    "Österreichische Datenschutzbehörde",
    
    # Ireland
    "Data Protection Commission",
    "DPC",
    
    # Sweden
    "Integritetsskyddsmyndigheten",
    "IMY",
    
    # Denmark
    "Datatilsynet",
    
    # Finland
    "Tietosuojavaltuutetun toimisto",
    
    # Portugal
    "Comissão Nacional de Proteção de Dados",
    "CNPD",
    
    # Greece
    "Hellenic Data Protection Authority",
    "HDPA",
    
    # Czech Republic
    "Úřad pro ochranu osobních údajů",
    "ÚOOÚ",
    
    # Romania
    "Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal",
    "ANSPDCP",
    
    # Hungary
    "Nemzeti Adatvédelmi és Információszabadság Hatóság",
    "NAIH",
    
    # Slovakia
    "Úrad na ochranu osobných údajov",
    
    # Bulgaria
    "Commission for Personal Data Protection",
    "CPDP",
    
    # Croatia
    "Agencija za zaštitu osobnih podataka",
    "AZOP",
    
    # Lithuania
    "Valstybinė duomenų apsaugos inspekcija",
    "VDAI",
    
    # Latvia
    "Datu valsts inspekcija",
    "DVI",
    
    # Estonia
    "Andmekaitse Inspektsioon",
    "AKI",
    
    # Slovenia
    "Informacijski pooblaščenec",
    "IP",
    
    # Luxembourg
    "Commission Nationale pour la Protection des Données",
    
    # Malta
    "Office of the Information and Data Protection Commissioner",
    "IDPC",
    
    # Cyprus
    "Commissioner for Personal Data Protection",
]

# Time-related terms that may be incorrectly flagged as names
time_terms = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    
    # German
    "Januar", "Februar", "März", "April", "Mai", "Juni",
    "Juli", "August", "September", "Oktober", "November", "Dezember",
    "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag",
    
    # French
    "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
    "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre",
    "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche",
    
    # Spanish
    "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
    "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre",
    "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo",
    
    # Italian
    "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno",
    "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre",
    "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica",
    
    # Dutch
    "Januari", "Februari", "Maart", "April", "Mei", "Juni",
    "Juli", "Augustus", "September", "Oktober", "November", "December",
    "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag",
    
    # Polish
    "Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec",
    "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień",
    "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela",
]

# Custom exclusions - add your own domain-specific terms here
custom = [
    "Bear AI",
    "BEAR-LLM",
    "Claude",
    "Anthropic",
]

[settings]
# Case-sensitive matching (false = ignore case differences)
case_sensitive = false

# Minimum confidence threshold for PII detection (0.0 - 1.0)
# Lower values = more aggressive detection
# Higher values = more lenient detection
min_confidence = 0.5

# Enable fuzzy matching for exclusions (experimental)
# May catch variations of excluded terms
fuzzy_matching = false