# PII Exclusions Configuration - English (UK/US)
# This file defines terms and patterns that should NOT be flagged as PII
# Prevents legal terms, common locations, and standard phrases from being redacted
# Region: English-speaking countries (UK, US, Ireland, Canada, Australia, New Zealand)

[exclusions]

# ============================================================================
# UNITED STATES
# ============================================================================

# US Geographic locations and jurisdictions
us_locations = [
    "United States", "United States of America", "USA",
    # States
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi",
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma",
    "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming",
    # Territories
    "District of Columbia", "Washington DC", "Puerto Rico", "Guam",
    "US Virgin Islands", "American Samoa", "Northern Mariana Islands",
    # Major Cities
    "New York City", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia",
    "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville",
    "Fort Worth", "Columbus", "Indianapolis", "Charlotte", "San Francisco",
    "Seattle", "Denver", "Boston", "Nashville", "El Paso", "Detroit", "Portland",
    "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque",
    "Tucson", "Fresno", "Sacramento", "Kansas City", "Miami", "Atlanta",
]

# US Courts and legal venues
us_courts = [
    "Supreme Court", "Supreme Court of the United States", "SCOTUS",
    "Federal Court", "United States District Court",
    "Court of Appeals", "United States Court of Appeals",
    "Circuit Court", "First Circuit", "Second Circuit", "Third Circuit",
    "Fourth Circuit", "Fifth Circuit", "Sixth Circuit", "Seventh Circuit",
    "Eighth Circuit", "Ninth Circuit", "Tenth Circuit", "Eleventh Circuit",
    "DC Circuit", "Federal Circuit",
    "Northern District", "Southern District", "Eastern District", "Western District",
    "Middle District", "Central District",
    "Bankruptcy Court", "Tax Court", "Court of Federal Claims",
    "Court of International Trade", "Foreign Intelligence Surveillance Court",
    "FISC", "Judicial Panel on Multidistrict Litigation",
]

# US Legal terms and constitutional references
us_legal_terms = [
    # Constitution & Amendments
    "United States Constitution", "Constitution", "Bill of Rights",
    "First Amendment", "Second Amendment", "Third Amendment", "Fourth Amendment",
    "Fifth Amendment", "Sixth Amendment", "Seventh Amendment", "Eighth Amendment",
    "Ninth Amendment", "Tenth Amendment", "Eleventh Amendment", "Twelfth Amendment",
    "Thirteenth Amendment", "Fourteenth Amendment", "Fifteenth Amendment",
    "Due Process Clause", "Equal Protection Clause", "Commerce Clause",
    "Supremacy Clause", "Necessary and Proper Clause",
    # Legal Doctrines
    "Stare Decisis", "Judicial Review", "Separation of Powers", "Checks and Balances",
    "Federalism", "Preemption", "Qualified Immunity", "Sovereign Immunity",
    # Legal Roles
    "Chief Justice", "Associate Justice", "Circuit Judge", "District Judge",
    "Magistrate Judge", "Bankruptcy Judge", "Attorney General", "Solicitor General",
    "United States Attorney", "Assistant United States Attorney", "AUSA",
    "District Attorney", "Assistant District Attorney", "ADA",
    "Public Defender", "Court-Appointed Attorney",
    # Legal Procedures
    "Summary Judgment", "Motion to Dismiss", "Class Action", "Habeas Corpus",
    "Plea Bargain", "Grand Jury", "Petit Jury", "Voir Dire", "Discovery",
    "Deposition", "Interrogatories", "Subpoena", "Warrant", "Injunction",
    "Temporary Restraining Order", "TRO", "Preliminary Injunction",
    # Evidence
    "Hearsay", "Best Evidence Rule", "Chain of Custody", "Privilege",
    "Attorney-Client Privilege", "Work Product Doctrine", "Spousal Privilege",
]

# US Government organizations and agencies
us_organizations = [
    "United States Government", "Federal Government", "US Government",
    # Executive Departments
    "Department of Justice", "DOJ", "Department of State", "State Department",
    "Department of Defense", "DOD", "Pentagon", "Department of Treasury",
    "Department of Homeland Security", "DHS", "Department of Commerce",
    "Department of Labor", "Department of Health and Human Services", "HHS",
    "Department of Education", "Department of Energy", "DOE",
    "Department of Veterans Affairs", "VA", "Department of Agriculture", "USDA",
    "Department of Interior", "Department of Transportation", "DOT",
    # Intelligence & Law Enforcement
    "Federal Bureau of Investigation", "FBI", "Central Intelligence Agency", "CIA",
    "National Security Agency", "NSA", "Defense Intelligence Agency", "DIA",
    "Drug Enforcement Administration", "DEA", "Bureau of Alcohol, Tobacco, Firearms and Explosives", "ATF",
    "United States Marshals Service", "USMS", "Secret Service",
    "Transportation Security Administration", "TSA", "Customs and Border Protection", "CBP",
    "Immigration and Customs Enforcement", "ICE",
    # Regulatory Agencies
    "Securities and Exchange Commission", "SEC", "Federal Trade Commission", "FTC",
    "Federal Communications Commission", "FCC", "Federal Aviation Administration", "FAA",
    "Food and Drug Administration", "FDA", "Environmental Protection Agency", "EPA",
    "Equal Employment Opportunity Commission", "EEOC", "National Labor Relations Board", "NLRB",
    "Consumer Financial Protection Bureau", "CFPB", "Commodity Futures Trading Commission", "CFTC",
    "Federal Energy Regulatory Commission", "FERC", "Nuclear Regulatory Commission", "NRC",
    # Financial Regulators
    "Federal Reserve", "Federal Reserve Board", "Federal Reserve System", "The Fed",
    "Office of the Comptroller of the Currency", "OCC", "Federal Deposit Insurance Corporation", "FDIC",
    "National Credit Union Administration", "NCUA",
    # Other Important Agencies
    "Internal Revenue Service", "IRS", "Social Security Administration", "SSA",
    "Small Business Administration", "SBA", "National Aeronautics and Space Administration", "NASA",
    "National Science Foundation", "NSF", "National Institutes of Health", "NIH",
]

# ============================================================================
# UNITED KINGDOM
# ============================================================================

# UK Geographic locations and jurisdictions
uk_locations = [
    "United Kingdom", "Great Britain", "Britain", "UK", "GB",
    # Countries
    "England", "Scotland", "Wales", "Northern Ireland",
    "Cymru", "Alba", "Tuaisceart Éireann",
    # Major Cities - England
    "London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Sheffield",
    "Bristol", "Newcastle", "Nottingham", "Leicester", "Southampton", "Brighton",
    "Portsmouth", "Reading", "Cambridge", "Oxford", "York", "Bath", "Canterbury",
    "Durham", "Chester", "Exeter", "Norwich", "Plymouth", "Gloucester", "Winchester",
    # Major Cities - Scotland
    "Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth",
    # Major Cities - Wales
    "Cardiff", "Swansea", "Newport", "Wrexham", "Bangor", "St Davids",
    # Major Cities - Northern Ireland
    "Belfast", "Derry", "Londonderry", "Lisburn", "Newry", "Armagh",
    # Historic Counties - England (selection)
    "Yorkshire", "Lancashire", "Kent", "Essex", "Sussex", "Cornwall", "Devon",
    "Somerset", "Dorset", "Hampshire", "Surrey", "Berkshire", "Oxfordshire",
    "Cambridgeshire", "Norfolk", "Suffolk", "Lincolnshire", "Nottinghamshire",
    "Derbyshire", "Staffordshire", "Cheshire", "Shropshire", "Worcestershire",
    "Warwickshire", "Leicestershire", "Northamptonshire", "Buckinghamshire",
]

# UK Courts and legal venues
uk_courts = [
    "Supreme Court of the United Kingdom", "UKSC", "UK Supreme Court",
    "Court of Appeal", "Court of Appeal (Civil Division)", "Court of Appeal (Criminal Division)",
    "High Court", "High Court of Justice", "Queen's Bench Division", "King's Bench Division",
    "Chancery Division", "Family Division",
    "Crown Court", "Old Bailey", "Central Criminal Court",
    "Magistrates' Court", "Youth Court", "Family Court",
    "County Court", "Employment Tribunal", "Employment Appeal Tribunal",
    # Scotland
    "Court of Session", "High Court of Justiciary", "Sheriff Court", "Sheriff Appeal Court",
    "Justice of the Peace Court",
    # Northern Ireland
    "Court of Judicature", "High Court of Justice in Northern Ireland",
    "Crown Court in Northern Ireland", "Magistrates' Court in Northern Ireland",
    # Specialized
    "Coroner's Court", "Tribunals", "Upper Tribunal", "First-tier Tribunal",
    "Competition Appeal Tribunal", "Investigatory Powers Tribunal",
]

# UK Legal terms
uk_legal_terms = [
    # Data Protection
    "Data Protection Act", "DPA 2018", "Data Protection Act 2018",
    "UK GDPR", "UK General Data Protection Regulation",
    "Information Commissioner's Office", "ICO",
    "Data Protection Officer", "DPO", "Data Controller", "Data Processor",
    "Subject Access Request", "SAR", "Data Subject",
    "Right to be Forgotten", "Right to Erasure", "Right to Portability",
    "Lawful Basis", "Legitimate Interest", "Consent",
    "Privacy and Electronic Communications Regulations", "PECR",
    # Freedom of Information
    "Freedom of Information Act", "FOIA", "Freedom of Information Act 2000",
    "Environmental Information Regulations", "EIR",
    # Constitutional & Historic
    "Magna Carta", "Bill of Rights 1689", "Act of Settlement 1701",
    "Human Rights Act", "Human Rights Act 1998", "European Convention on Human Rights",
    "Parliamentary Sovereignty", "Rule of Law", "Constitutional Monarchy",
    # Legal Systems
    "Common Law", "Statute Law", "Statutory Instrument", "Case Law",
    "Precedent", "Binding Precedent", "Persuasive Precedent",
    "Equity", "Equitable Remedies",
    # Legal Professions
    "Queen's Counsel", "King's Counsel", "QC", "KC", "Silk",
    "Solicitor", "Barrister", "Advocate", "Solicitor Advocate",
    "Legal Executive", "Chartered Legal Executive", "Paralegal",
    "Pupil Barrister", "Trainee Solicitor",
    # Legal Offices
    "Lord Chancellor", "Attorney General", "Solicitor General",
    "Director of Public Prosecutions", "DPP", "Lord Chief Justice",
    "Master of the Rolls", "Lord Justice", "Lady Justice",
    # Prosecution & Enforcement
    "Crown Prosecution Service", "CPS", "Serious Fraud Office", "SFO",
    "Crown Prosecution Service", "Procurator Fiscal", "Public Prosecution Service",
    # Regulatory Bodies
    "Financial Conduct Authority", "FCA", "Prudential Regulation Authority", "PRA",
    "Competition and Markets Authority", "CMA", "Office of Communications", "Ofcom",
    "Office of Gas and Electricity Markets", "Ofgem", "Office of Water Services", "Ofwat",
    "Health and Safety Executive", "HSE", "Equality and Human Rights Commission", "EHRC",
    # Legal Procedures
    "Judicial Review", "Leave to Appeal", "Permission to Appeal",
    "Defendant", "Claimant", "Plaintiff", "Respondent", "Appellant",
    "Writ", "Summons", "Injunction", "Interim Injunction", "Final Injunction",
    "Disclosure", "CPR", "Civil Procedure Rules",
]

# UK Government organizations
uk_organizations = [
    "Her Majesty's Government", "His Majesty's Government", "HM Government",
    "Cabinet Office", "Treasury", "HM Treasury", "HM Revenue and Customs", "HMRC",
    "Home Office", "Foreign Office", "Foreign, Commonwealth and Development Office", "FCDO",
    "Ministry of Defence", "MOD", "Ministry of Justice", "MOJ",
    "Department for Education", "Department of Health and Social Care",
    "Department for Business and Trade", "Department for Transport",
    "Department for Environment, Food and Rural Affairs", "DEFRA",
    "Department for Work and Pensions", "DWP", "Department for Energy Security and Net Zero",
    "Department for Science, Innovation and Technology",
    "Ministry of Housing, Communities and Local Government",
    # Intelligence & Security
    "Secret Intelligence Service", "SIS", "MI6", "Security Service", "MI5",
    "Government Communications Headquarters", "GCHQ", "Defence Intelligence", "DI",
    # Law Enforcement
    "Metropolitan Police", "Met Police", "City of London Police",
    "National Crime Agency", "NCA", "Police Service of Northern Ireland", "PSNI",
    "Police Scotland", "British Transport Police",
    # Other Bodies
    "National Health Service", "NHS", "BBC", "British Broadcasting Corporation",
    "Bank of England", "UK Parliament", "House of Commons", "House of Lords",
]

# ============================================================================
# OTHER ENGLISH-SPEAKING REGIONS
# ============================================================================

# Ireland
ireland_terms = [
    "Republic of Ireland", "Ireland", "Éire", "Irish Republic",
    "Dublin", "Cork", "Galway", "Limerick", "Waterford", "Drogheda", "Dundalk",
    "Oireachtas", "Dáil Éireann", "Seanad Éireann",
    "Supreme Court of Ireland", "High Court of Ireland", "Circuit Court", "District Court",
    "Data Protection Commission", "DPC", "Data Protection Commissioner",
    "Irish Data Protection Act", "GDPR", "General Data Protection Regulation",
    "An Garda Síochána", "Gardaí", "Garda",
    "Taoiseach", "Tánaiste", "Attorney General",
]

# Canada
canada_terms = [
    "Canada", "Canadian",
    # Provinces & Territories
    "Ontario", "Quebec", "Québec", "British Columbia", "Alberta", "Manitoba",
    "Saskatchewan", "Nova Scotia", "New Brunswick", "Newfoundland and Labrador",
    "Prince Edward Island", "Northwest Territories", "Nunavut", "Yukon",
    # Major Cities
    "Toronto", "Montreal", "Montréal", "Vancouver", "Calgary", "Edmonton",
    "Ottawa", "Winnipeg", "Quebec City", "Ville de Québec", "Halifax",
    # Courts
    "Supreme Court of Canada", "Federal Court of Canada", "Tax Court of Canada",
    "Provincial Court", "Superior Court",
    # Legal & Government
    "Privacy Commissioner", "Office of the Privacy Commissioner of Canada", "PIPEDA",
    "Personal Information Protection and Electronic Documents Act",
    "Canadian Charter of Rights and Freedoms", "Charter of Rights",
    "Parliament of Canada", "House of Commons", "Senate",
    "Royal Canadian Mounted Police", "RCMP",
]

# Australia
australia_terms = [
    "Australia", "Australian", "Commonwealth of Australia",
    # States & Territories
    "New South Wales", "NSW", "Victoria", "VIC", "Queensland", "QLD",
    "South Australia", "SA", "Western Australia", "WA", "Tasmania", "TAS",
    "Northern Territory", "NT", "Australian Capital Territory", "ACT",
    # Major Cities
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra",
    "Gold Coast", "Newcastle", "Hobart", "Darwin", "Wollongong",
    # Courts
    "High Court of Australia", "Federal Court of Australia", "Family Court of Australia",
    "Supreme Court", "District Court", "Magistrates Court",
    # Legal & Government
    "Office of the Australian Information Commissioner", "OAIC",
    "Privacy Act 1988", "Australian Privacy Principles", "APP",
    "Australian Constitution", "Commonwealth of Australia Constitution Act",
    "Parliament of Australia", "Australian Parliament",
    "Australian Federal Police", "AFP",
]

# New Zealand
newzealand_terms = [
    "New Zealand", "Aotearoa", "NZ",
    # Regions
    "Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin", "Tauranga",
    "North Island", "South Island", "Te Ika-a-Māui", "Te Waipounamu",
    # Courts
    "Supreme Court of New Zealand", "Court of Appeal of New Zealand",
    "High Court of New Zealand", "District Court of New Zealand",
    # Legal & Government
    "Privacy Commissioner", "Office of the Privacy Commissioner",
    "Privacy Act 2020", "Privacy Act 1993",
    "New Zealand Bill of Rights Act", "Treaty of Waitangi",
    "Parliament of New Zealand", "New Zealand Parliament",
]

# ============================================================================
# COMMON TERMS (ALL ENGLISH REGIONS)
# ============================================================================

# Time-related terms (English)
time_terms = [
    # Months
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
    # Abbreviated months
    "Jan", "Feb", "Mar", "Apr", "Jun", "Jul", "Aug", "Sep", "Sept", "Oct", "Nov", "Dec",
    # Days
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    # Abbreviated days
    "Mon", "Tue", "Tues", "Wed", "Thu", "Thur", "Thurs", "Fri", "Sat", "Sun",
    # Seasons
    "Spring", "Summer", "Autumn", "Fall", "Winter",
    # Time periods
    "Quarter", "Q1", "Q2", "Q3", "Q4", "Fiscal Year", "Calendar Year",
]

# Common legal terms (all English jurisdictions)
common_legal_terms = [
    "Plaintiff", "Defendant", "Claimant", "Respondent", "Appellant", "Appellee",
    "Petitioner", "Witness", "Expert Witness", "Fact Witness",
    "Counsel", "Attorney", "Lawyer", "Advocate", "Legal Representative",
    "Judge", "Magistrate", "Justice", "Tribunal", "Arbitrator", "Mediator",
    "Jury", "Juror", "Foreman", "Grand Jury", "Petit Jury",
    "Contract", "Agreement", "Deed", "Lease", "License", "Covenant",
    "Tort", "Negligence", "Breach", "Damages", "Liability", "Indemnity",
    "Statute", "Regulation", "Ordinance", "By-law", "Code",
    "Affidavit", "Declaration", "Sworn Statement", "Testimony",
    "Evidence", "Exhibit", "Document", "Record", "Transcript",
]

# Custom exclusions
custom = [
    "Bear AI", "BEAR-LLM", "BEAR AI", "Claude", "Anthropic",
]

# ============================================================================
# SETTINGS
# ============================================================================

[settings]
# Case-sensitive matching (false = ignore case differences)
case_sensitive = false

# Minimum confidence threshold for PII detection (0.0 - 1.0)
# Lower values = more aggressive detection
# Higher values = more lenient detection
min_confidence = 0.5

# Enable fuzzy matching for exclusions (experimental)
# May catch variations of excluded terms
fuzzy_matching = false

# Region identifier
region = "en"
description = "English language exclusions (UK, US, Ireland, Canada, Australia, New Zealand)"
