# Cargo configuration for BEAR-LLM
# Pure Rust build - no special MSVC runtime configuration needed

[build]
# Incremental compilation disabled for release builds
incremental = false

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=-crt-static"]