[net]
retry = 2
git-fetch-with-cli = true

[build]
target-dir = "target"

# No special Windows MSVC configuration needed
# Pure Rust Candle builds reliably without CRT linking tweaks

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=-crt-static"]