[net]
retry = 2
git-fetch-with-cli = true

[build]
target-dir = "target"

# Windows MSVC runtime library configuration
# Use STATIC CRT to resolve LNK2038 mismatch errors
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static"
]