[net]
retry = 2
git-fetch-with-cli = true

[build]
target-dir = "target"

# Windows MSVC runtime library configuration
# Use DYNAMIC CRT to match llama_cpp_sys (MD_DynamicRelease)
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=-crt-static"
]