name: Fast Release Build

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (leave empty for Cargo.toml version)'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  fast-build:
    name: Quick Windows Build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(grep -m1 '^version' src-tauri/Cargo.toml | cut -d'"' -f2)" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-fast-${{ hashFiles('**/Cargo.lock') }}

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v${{ steps.version.outputs.version }}
          releaseName: 'BEAR AI v${{ steps.version.outputs.version }}'
          releaseBody: |
            🐻 BEAR AI v${{ steps.version.outputs.version }}
            
            **Quick Release Build**
            - Download BEAR-AI_x64-setup.exe (NSIS installer)
            - Or BEAR-AI_x64_en-US.msi (MSI installer)
            
            Run as Administrator for best experience.
          releaseDraft: true
          prerelease: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
